apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: monitoring

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 77.5.0

    helm:
      values: |
        grafana:
          enabled: true

          grafana.ini:
            server:
              root_url: http://a530133478f634f929d2334b791ac380-113203296.us-east-2.elb.amazonaws.com/
              serve_from_sub_path: false

            auth.anonymous:
              enabled: false

        prometheus:
          enabled: true

        alertmanager:
          enabled: true

        nodeExporter:
          enabled: true

        kubeStateMetrics:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
