replicaCount: 2

image:
  repository: 806997204926.dkr.ecr.us-east-2.amazonaws.com/user-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  NODE_ENV: development

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu:
    targetUtilization: 60

serviceAccount:
  create: true
  name: user-service-sa
