apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "payment-service.fullname" . }}
  namespace: {{ .Release.Namespace }}

  labels:
    app: {{ include "payment-service.name" . }}

spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: {{ include "payment-service.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "payment-service.name" . }}

    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      containers:
        - name: payment-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}

          env:
            - name: VERSION
              value: "{{ .Values.image.tag }}"

          envFrom:
            - configMapRef:
                name: {{ include "payment-service.fullname" . }}-config

            - secretRef:
                name: {{ include "payment-service.fullname" . }}-secret

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /health
              port: http

            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: http

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
