apiVersion: v1
kind: Secret

metadata:
  name: {{ include "order-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  PAYMENT_API_KEY: {{ .Values.secret.PAYMENT_API_KEY | quote }}
